### PR TITLE
Add lab contact info

### PR DESCRIPTION
**Pull request by ben9583**
Adds a facilitator title to each lab using facilitator list from the Google Doc. If there isn't a slot in the spreadsheet, the facilitator is ignored. There were also some facilitators I didn't know which profile to put for them, so I left blank.

Each lab markdown has a new `facilitator` property. It should be their name in their associated `_staffer` markdown file:
```md
---
title: Lab a1 - Shell Scripting
layout: lab
facilitator: Ben Cuan
nav_exclude: true
---

...
```

If no facilitator, it is null:
```md
---
title: Lab 6 - Processes and Services
layout: lab
facilitator: null
nav_exclude: true
---

...
```

Example:

Clicking on the link will take the viewer to the staff page at the location of the staffer with a spotlight effect around them:

If no facilitator found, page will appear as normal:

I haven't been able to get Jekyll cooperatively working with my host and domain so it would be best to get hosted before. Also it may be good to address those labs with people assigned to facilitate, but no associated file (as far as I know) in `_staffers` (njha, ajanse, etc.).

### CODE REVIEW

**Comment by laksith19** [comment]
lgtm! And great feature! I've just merged in the master branch and hosted if for the moment [here](http://supernova.ocf.berkeley.edu:8595//) on supernova.

**Review by 64bitpandas — CHANGES_REQUESTED** [review]
Wow looks great! Thanks for making this.

Small change requested - could you make it say something like 'facilitator in charge' or 'presenter' etc rather than 'by'? It's not entirely accurate since the original author(s) of the lab is likely different from whoever is running it this semester. (maybe as a future feature we could scrape github history and put lab credits somewhere lol)

**Comment by ben9583** [comment]
Glad y’all like it! I’ve gone ahead and changed the attribution to “facilitator:” instead. Should all be good then.

**Comment by laksith19** [comment]
Supernova has also been updated!

**Review by 64bitpandas — APPROVED** [review]
lgtm! merging

**Pull request merged**
