### PR TITLE
Expand dark mode to main pages

### PR DESCRIPTION
**Pull request by ben9583**
Adds a button to the bottom left of the page that lets the user toggle dark mode. By default, uses the system preference. Also uses a cookie to track the user's preference that extends to the lab pages as well.

Preview (zoomed out to include more elements):
Screen Shot 2021-09-21 at 9 51 45 PM

### CODE REVIEW

**Comment by laksith19** [comment]
I’m pretty sure this was up last semester but @64bitpandas removed it because the font on the search was still black and hard to read.

**Comment by ben9583** [comment]
Ah, that makes sense. I'll see what I can do on that end.

**Comment by ben9583** [comment]
New look:
Screen Shot 2021-09-21 at 11 13 40 PM

Thoughts?

**Comment by laksith19** [comment]
Seems much better! I've hosted it [here](http://supernova.ocf.berkeley.edu:8595/) for the time being. Seems great except for very minor things like the date of the the announcements etc... Let's check with @64bitpandas and then merge.

**Review by 64bitpandas — APPROVED** [review]
This looks awesome, thank you for making this! Ready to merge

**Pull request merged**
