### PR TITLE
Lab a4 link fix

### PR DESCRIPTION
**Pull request by Hexhu**
- fix link to selinuxproject.org, otherwise it jumps to https://decal.ocf.berkeley.edu/labs/selinunxproject.org
- change http links to https

### CODE REVIEW

**Review by 64bitpandas — APPROVED** [review]
lgtm, thanks for the fix!

**Comment by Hexhu** [comment]
@64bitpandas I don't have write access. Can you squash and merge on my behalf?

**Comment by 64bitpandas** [comment]
Ok! I sent you an invite btw so you can merge in the future

**Comment by Hexhu** [comment]
Thanks!

**Pull request merged**
